package com.edu.unlu.generala.modelos;

public enum EventoPartida {
    RONDA_TIRADAS,
    RONDA_APUESTAS,
    JUGADOR_AGREGADO,
    JUEGO_INICIADO,
    DADOS_TIRADOS,
    CAMBIO_TURNO,
    TODOS_PLANTADOS,
    GANADOR_DETERMINADO,
    RONDA_APUESTAS_INICIADA,
    APUESTA_IGUALADA,
    APUESTA_SUBIDA,
    APOSTADOR_PLANTADO,
    SIGUIENTE_APOSTADOR,
    ACTUALIZAR_MENU_DADOS,
}
